alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias dotfiles="/usr/bin/git --git-dir=${HOME}/.dotfiles --work-tree=${HOME}"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias gacp="git add -A && git commit -m '.' && git push"
alias nvim="NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim"
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0 |grep -E "state|to\ full|percentage"'
alias cls="clear; printf '\033[3J'"
# some more ls aliases
#alias l= "ls -CF"
alias ll="ls -alF"
alias la="ls -A"
alias lr="ls -althr"
alias lh="ls -ld .?*"
alias vfwork="GIT_WORK_TREE=/mnt/c/Users/Kafein/Documents/notes/is GIT_DIR=$WORKFILES_DIR"
alias lr="ls -alhtr"
alias random="tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo"
alias tmuxn="tmux new-session -s devops"
