# General behavior
set -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB,screen-256color:RGB,tmux-256color:RGB"
set -g history-file ~/.tmux_history
set -g history-limit 100000
set -sg escape-time 10
set -g focus-events on
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi

# Status bar toggle
bind-key -n C-f3 if -F "#{==:#{status},on}" "set -g status off" "set -g status on"

# Prompt for a command and open a wide vertical split in the current directory
bind-key x command-prompt -p "split-window:" "split-window -c '#{pane_current_path}' '%%' -p 76"

# Son pencereler arasinda gezinme
bind ^B last-window

# Pane resizing and vim-aware navigation
unbind C-Left
bind -n C-Left resize-pane -L 10
unbind C-Right
bind -n C-Right resize-pane -R 10
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|/)g?(view|vim?x?)$' && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|/)g?(view|vim?x?)$' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|/)g?(view|vim?x?)$' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|/)g?(view|vim?x?)$' && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-o send-keys -R Enter \; clear-history

# update VSCODE variables from integrated terminal so that `code` opens in the
# current window from inside tmux
set -ga update-environment 'VSCODE_GIT_ASKPASS_NODE VSCODE_GIT_ASKPASS_MAIN VSCODE_IPC_HOOK_CLI PATH GIT_ASKPASS'

# Toggle synchronize-panes with Ctrl-b + a and show state
bind-key a setw synchronize-panes \; display-message "synchronize-panes #{?pane_synchronized,on,off}"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
