---
exclude: (^|/)wwwroot/lib/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - >-
            --config-data={"extends":"default","rules":{"comments":
            {"min-spaces-from-content":1},"comments-indentation":"disable",
            "document-start":"disable","indentation":{"spaces":2,
            "indent-sequences":"consistent","check-multi-line-strings":false},
            "line-length":"disable","new-line-at-end-of-file":"disable",
            "trailing-spaces":"disable","truthy":"disable"}}

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-jsonschema
        name: Validate bitbucket-pipelines.yml against Bitbucket's schema
        files: ^bitbucket-pipelines\.yml$
        args:
          - --schemafile
          - https://api.bitbucket.org/schemas/pipelines-configuration
